require 'spec_helper'

describe Transcribe::FlagAiUse do
  let!(:owner) { create(:unique_user, :owner) }
  let!(:user) { create(:unique_user) }
  let!(:collection) { create(:collection, owner_user_id: owner.id) }

  let!(:work) { create(:work, collection: collection, owner_user_id: owner.id) }
  let!(:page) { create(:page, work: work, source_text: source_text) }

  let!(:ai_transcription) { create(:ai_transcription, page_id: page.id, status: :finished, source_text: "<!-- The following text was generated by artificial intelligence and probably contains errors. (Please delete this warning.) -->\nThis is an AI Generated text") }

  let(:source_text) { "Clean Text" }

  let(:result) do
    described_class.new(
      page: page,
      user: user
    ).call
  end

  it 'does not create suspicious_behavior' do
    expect { result }.not_to change { SuspiciousBehavior.count }

    expect(result.success?).to be_truthy
  end

  context 'with AI warning text left' do
    let(:source_text) { "<!-- The following text was generated by artificial intelligence and probably contains errors. (Please delete this warning.) -->\nUnclean Text" }

    it 'creates suspicious_behavior' do
      expect { result }.to change { SuspiciousBehavior.count }.by(1)

      expect(result.success?).to be_truthy
      expect(page.suspicious_behaviors.first.behavior_type.to_sym).to eq(:ai_warning_left)
    end
  end

  context 'with minimal changes from AI draft' do
    let(:source_text) { "This is an AI Generated text" }

    it 'creates suspicious_behavior' do
      expect { result }.to change { SuspiciousBehavior.count }.by(1)

      expect(result.success?).to be_truthy
      expect(page.suspicious_behaviors.first.behavior_type.to_sym).to eq(:minimal_ai_changes)
    end
  end
end
