#!/usr/bin/env ruby

# We need to make our own Rails.root here because
# this file is started outside of rails.
unless defined?(Rails.root)
  root_path = File.join(File.dirname(__FILE__), '../..')
  unless RUBY_PLATFORM =~ /mswin32/
    require 'pathname'
    root_path = Pathname.new(root_path).cleanpath(true).to_s
  end
  Rails.root = root_path
end

pid = File.open("#{Rails.root}/log/backgroundrb.pid"){|f| f.read.chomp.to_i }

Process.kill(9, pid)
