RSpec/IndexedLet:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/AroundBlock:
  Enabled: true

RSpec/Be:
  Enabled: false

RSpec/BeEql:
  Enabled: true

RSpec/BeforeAfterAll:
  Enabled: true

RSpec/ContextMethod:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: true

RSpec/DescribeSymbol:
  Enabled: true

RSpec/DescribedClass:
  Enabled: false

RSpec/DescribedClassModuleWrapping:
  Enabled: true

RSpec/Dialect:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/EmptyHook:
  Enabled: true

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/ExpectOutput:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/Focus:
  Enabled: true

RSpec/HookArgument:
  Enabled: false

RSpec/HooksBeforeExamples:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false

RSpec/ImplicitBlockExpectation:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/InstanceSpy:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ItBehavesLike:
  Enabled: false

RSpec/IteratedExpectation:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MissingExampleGroupArgument:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleSubjects:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/OverwritingSetup:
  Enabled: false

RSpec/Pending:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/ReceiveCounts:
  Enabled: false

RSpec/ReceiveNever:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/RepeatedIncludeExample:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/SharedContext:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

RSpec/SingleArgumentMessageChain:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/UnspecifiedException:
  Enabled: false

RSpec/VariableDefinition:
  Enabled: false

RSpec/VariableName:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/VoidExpect:
  Enabled: false

RSpec/Yield:
  Enabled: false

RSpec/ChangeByZero:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/MetadataStyle:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - !ruby/regexp /lint_spec.rb/
