Rails/LexicallyScopedActionFilter:
  Exclude:
    - !ruby/regexp /concern/
    - !ruby/regexp /base/

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/ApplicationMailer:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/ApplicationController:
  Enabled: false

Rails/UnknownEnv:
  Environments: [development, test, production, local]

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/RedundantActiveRecordAllMethod:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false
