Naming/PredicateName:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false
