Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Max: 300
  Exclude:
    - !ruby/regexp /models/
    - !ruby/regexp /controllers/

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
