FROM ruby:3.3.5

RUN apt-get update -qq && \
    apt-get install -y \
      ghostscript \
      poppler-utils \
      graphviz \
      pandoc \
      texlive-base \
      texlive-latex-base \
      texlive-latex-recommended \
      texlive-fonts-recommended \
      texlive-latex-extra \
      texlive-xetex \
      texlive-luatex \
      libmagickwand-dev \
      imagemagick \
      nodejs \
      npm \
      xauth \
      xvfb \
      x11-xserver-utils \
      chromium \
      chromium-driver \
      pdf2svg \
      fonts-cmu \
    && rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
ENV NODE_PATH=/usr/local/lib/node_modules
RUN npm install -g puppeteer@24.42.0 --omit=dev

WORKDIR /app
