FROM ruby:2.7.3

RUN apt-get update -qq && \
    apt-get install -y \
      ghostscript \
      poppler-utils \
      graphviz \
      pandoc \
      texlive-full \
      libmagickwand-dev \
      imagemagick \
      default-mysql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENTRYPOINT ["/bin/bash"]
