#You have to configure here your environment var

DATABASE_HOST: "127.0.0.1"
DATABASE_USERNAME: "root"
DATABASE_PASSWORD: "mypassword"

#Configuration of metagame\
METAGAME_PROJECT_NAME: "projectname"
METAGAME_URL: "metagameBaseUrl"
METAGAME_TOKEN: "metagameToken"
