# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 25) do

  create_table "article_article_links", :force => true do |t|
    t.column "source_article_id", :integer
    t.column "target_article_id", :integer
    t.column "display_text",      :string
    t.column "created_on",        :datetime
  end

  create_table "article_versions", :force => true do |t|
    t.column "title",       :string
    t.column "source_text", :text
    t.column "xml_text",    :text
    t.column "user_id",     :integer
    t.column "article_id",  :integer
    t.column "version",     :integer,  :default => 0
    t.column "created_on",  :datetime
  end

  create_table "articles", :force => true do |t|
    t.column "title",         :string
    t.column "source_text",   :text
    t.column "created_on",    :datetime
    t.column "lock_version",  :integer,  :default => 0
    t.column "xml_text",      :text
    t.column "graph_image",   :string
    t.column "collection_id", :integer
  end

  create_table "articles_categories", :id => false, :force => true do |t|
    t.column "article_id",  :integer
    t.column "category_id", :integer
  end

  create_table "categories", :force => true do |t|
    t.column "title",         :string
    t.column "parent_id",     :integer
    t.column "collection_id", :integer
    t.column "created_on",    :datetime
  end

  create_table "collections", :force => true do |t|
    t.column "title",         :string
    t.column "owner_user_id", :integer
    t.column "created_on",    :datetime
  end

  create_table "comments", :force => true do |t|
    t.column "parent_id",        :integer
    t.column "user_id",          :integer
    t.column "created_at",       :datetime,                                         :null => false
    t.column "commentable_id",   :integer,                :default => 0,            :null => false
    t.column "commentable_type", :string,                 :default => "",           :null => false
    t.column "depth",            :integer
    t.column "title",            :string
    t.column "body",             :text
    t.column "comment_type",     :string,   :limit => 10, :default => "annotation"
    t.column "comment_status",   :string,   :limit => 10
  end

  create_table "image_sets", :force => true do |t|
    t.column "path",                      :string
    t.column "title_format",              :string
    t.column "created_on",                :datetime
    t.column "orientation",               :integer
    t.column "original_width",            :integer
    t.column "original_height",           :integer
    t.column "original_to_base_halvings", :integer
    t.column "owner_user_id",             :integer
  end

  create_table "page_article_links", :force => true do |t|
    t.column "page_id",      :integer
    t.column "article_id",   :integer
    t.column "display_text", :string
    t.column "created_on",   :datetime
  end

  create_table "page_versions", :force => true do |t|
    t.column "title",             :string
    t.column "transcription",     :text
    t.column "xml_transcription", :text
    t.column "user_id",           :integer
    t.column "page_id",           :integer
    t.column "work_version",      :integer,  :default => 0
    t.column "page_version",      :integer,  :default => 0
    t.column "created_on",        :datetime
  end

  create_table "pages", :force => true do |t|
    t.column "title",         :string
    t.column "source_text",   :text
    t.column "base_image",    :string
    t.column "base_width",    :integer
    t.column "base_height",   :integer
    t.column "shrink_factor", :integer
    t.column "work_id",       :integer
    t.column "created_on",    :datetime
    t.column "position",      :integer
    t.column "lock_version",  :integer,  :default => 0
    t.column "xml_text",      :text
  end

  create_table "titled_images", :force => true do |t|
    t.column "original_file",    :string,                 :default => "",    :null => false
    t.column "title_seed",       :string,   :limit => 20
    t.column "title_override",   :string
    t.column "title",            :string
    t.column "shrink_completed", :boolean,                :default => false
    t.column "rotate_completed", :boolean,                :default => false
    t.column "crop_completed",   :boolean,                :default => false
    t.column "image_set_id",     :integer
    t.column "position",         :integer
    t.column "created_on",       :datetime
    t.column "lock_version",     :integer,                :default => 0
  end

  create_table "transcribe_authorizations", :id => false, :force => true do |t|
    t.column "user_id", :integer
    t.column "work_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "display_name",              :string
    t.column "print_name",                :string
    t.column "email",                     :string
    t.column "owner",                     :boolean,                :default => false
    t.column "admin",                     :boolean,                :default => false
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

  create_table "works", :force => true do |t|
    t.column "title",                     :string
    t.column "description",               :text
    t.column "created_on",                :datetime
    t.column "owner_user_id",             :integer
    t.column "restrict_scribes",          :boolean,  :default => false
    t.column "transcription_version",     :integer,  :default => 0
    t.column "physical_description",      :text
    t.column "document_history",          :text
    t.column "permission_description",    :text
    t.column "location_of_composition",   :string
    t.column "author",                    :string
    t.column "transcription_conventions", :text
    t.column "collection_id",             :integer
  end

end
