require 'spec_helper'

describe Transcribe::FlagAiUseJob do
  let!(:owner) { create(:unique_user, :owner) }
  let!(:user) { create(:unique_user) }
  let!(:collection) { create(:collection, owner_user_id: owner.id) }

  let!(:work) { create(:work, collection: collection, owner_user_id: owner.id) }
  let!(:page) { create(:page, work: work, source_text: source_text) }

  let!(:ai_transcription) { create(:ai_transcription, page_id: page.id, status: :finished, source_text: source_text) }

  let(:source_text) { "<!-- The following text was generated by artificial intelligence and probably contains errors. (Please delete this warning.) -->\nThis is an AI Generated text" }

  subject(:worker) { described_class }

  let(:perform_worker) do
    worker.perform_now(page_id: page.id, user_id: user.id)
  end

  it 'enqueues GenerateJob for ai_transcriptions' do
    perform_worker

    expect(page.suspicious_behaviors).to match_array([
      have_attributes(
        behavior_type: 'ai_warning_left'
      ),
      have_attributes(
        behavior_type: 'minimal_ai_changes'
      )
    ])
  end
end
