require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DocumentUploadsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # DocumentUpload. As you add validations to DocumentUpload, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DocumentUploadsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all document_uploads as @document_uploads" do
      document_upload = DocumentUpload.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:document_uploads)).to eq([document_upload])
    end
  end

  describe "GET show" do
    it "assigns the requested document_upload as @document_upload" do
      document_upload = DocumentUpload.create! valid_attributes
      get :show, {:id => document_upload.to_param}, valid_session
      expect(assigns(:document_upload)).to eq(document_upload)
    end
  end

  describe "GET new" do
    it "assigns a new document_upload as @document_upload" do
      get :new, {}, valid_session
      expect(assigns(:document_upload)).to be_a_new(DocumentUpload)
    end
  end

  describe "GET edit" do
    it "assigns the requested document_upload as @document_upload" do
      document_upload = DocumentUpload.create! valid_attributes
      get :edit, {:id => document_upload.to_param}, valid_session
      expect(assigns(:document_upload)).to eq(document_upload)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DocumentUpload" do
        expect {
          post :create, {:document_upload => valid_attributes}, valid_session
        }.to change(DocumentUpload, :count).by(1)
      end

      it "assigns a newly created document_upload as @document_upload" do
        post :create, {:document_upload => valid_attributes}, valid_session
        expect(assigns(:document_upload)).to be_a(DocumentUpload)
        expect(assigns(:document_upload)).to be_persisted
      end

      it "redirects to the created document_upload" do
        post :create, {:document_upload => valid_attributes}, valid_session
        expect(response).to redirect_to(DocumentUpload.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved document_upload as @document_upload" do
        post :create, {:document_upload => invalid_attributes}, valid_session
        expect(assigns(:document_upload)).to be_a_new(DocumentUpload)
      end

      it "re-renders the 'new' template" do
        post :create, {:document_upload => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested document_upload" do
        document_upload = DocumentUpload.create! valid_attributes
        put :update, {:id => document_upload.to_param, :document_upload => new_attributes}, valid_session
        document_upload.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested document_upload as @document_upload" do
        document_upload = DocumentUpload.create! valid_attributes
        put :update, {:id => document_upload.to_param, :document_upload => valid_attributes}, valid_session
        expect(assigns(:document_upload)).to eq(document_upload)
      end

      it "redirects to the document_upload" do
        document_upload = DocumentUpload.create! valid_attributes
        put :update, {:id => document_upload.to_param, :document_upload => valid_attributes}, valid_session
        expect(response).to redirect_to(document_upload)
      end
    end

    describe "with invalid params" do
      it "assigns the document_upload as @document_upload" do
        document_upload = DocumentUpload.create! valid_attributes
        put :update, {:id => document_upload.to_param, :document_upload => invalid_attributes}, valid_session
        expect(assigns(:document_upload)).to eq(document_upload)
      end

      it "re-renders the 'edit' template" do
        document_upload = DocumentUpload.create! valid_attributes
        put :update, {:id => document_upload.to_param, :document_upload => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested document_upload" do
      document_upload = DocumentUpload.create! valid_attributes
      expect {
        delete :destroy, {:id => document_upload.to_param}, valid_session
      }.to change(DocumentUpload, :count).by(-1)
    end

    it "redirects to the document_uploads list" do
      document_upload = DocumentUpload.create! valid_attributes
      delete :destroy, {:id => document_upload.to_param}, valid_session
      expect(response).to redirect_to(document_uploads_url)
    end
  end

end
