require 'spec_helper'

# get method of: ActionController::TestCase::Behavior

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkController do

  before (:each) do
    # this works: 
    @user = FactoryGirl.create(:user)
    User.current_user = @user
    # this also works:
    # @user = User.new( :provider => "twitter", :uid => "12345", :name => "the user")
    # @user.save
  end
  let (:user) {
     # FactoryGirl.create(:user)
  }

  # This should return the minimal set of attributes required to create a valid
  # Website. As you add validations to Website, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :user_id => 1,
      :title => "valid-url-0000",
      :description => "lalala",
      :transcription_version => 2
    }
  end

  def valid_attributes_from_site(website_url)
    { :user_id => 1,
      :url => website_url,
      :failed_tries => 0,
      :successful_tries => 1,
      :good_site => true,
      :name => "CNN"
    }
  end

  def invalid_attributes
    { :user_id => 1,
      :url => "valid-url-0000.herokuapp.com/users/1/edit"
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WebsitesController. Be sure to keep this updated too.
  def valid_session
    {
      "user_id"=> @user.id,
      "user" => @user.id 
    }
  end

  def valid_session_from_user(user_id)
    {
      "user_id" => user_id
    }
  end

  def invalid_session 
    { 
    "user_id" => 5 
    }
  end

=begin
  describe "GET index" do
    it "assigns all websites as @websites" do
      website = Website.create! valid_attributes
      get :index, {}, valid_session
      assigns(:websites).should eq([website])
    end

  end

  describe "GET show" do
    it "assigns the requested website as @website" do
      website = Website.create! valid_attributes
      get :show, {:id => website.to_param}, valid_session
      assigns(:website).should eq(website)
    end
  end
=end
  describe "GET new" do
    it "assigns a new work as @work" do
      # aa = FactoryGirl.create(:work)
      get :new, {} # , valid_session
      # assigns(:work).should be_a_new(Work)
    end
  end
=begin
  describe "GET edit" do
    it "assigns the requested website as @website" do
      website = Website.create! valid_attributes
      get :edit, {:id => website.to_param}, valid_session
      assigns(:website).should eq(website)
    end
  end
=end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Work" do
        # this is the magic
        controller.class.skip_before_filter :authorized?
        
        expect {
          post :create, {:work => valid_attributes}, valid_session
        }.to change(Work, :count).by(1)
      end

      xit "assigns a newly created work as @work" do
        # @user = FactoryGirl.create(:user)
        # controller.current_user.should == @user
        # current_user.send(:user)
        obj = double()
        obj.stub(:current_user) { :user }

        controller.class.skip_before_filter :authorized?
        post :create, {:work => valid_attributes}, valid_session
        assigns(:work).should be_a(Work)
        assigns(:work).should be_persisted
      end

      xit "assigns a newly created work as string" do
        controller.class.skip_before_filter :authorized?
        post :create, {:work => valid_attributes}, valid_session
        assigns(:work).should be_a(Work)
        assigns(:work).should be_persisted
      end

      xit "redirects to the created website" do
        # post :create, {:website => valid_attributes}, valid_session
        # response.should redirect_to(Website.last)
      end

    end

    describe "with invalid params" do
      it "does not create a new Work" do
        # this is the magic
        # controller.class.skip_before_filter :authorized?
        
        expect {
          begin
            post :create, {:work => valid_attributes}, invalid_session
          rescue
          end
        }.to change(Work, :count).by(0)
      end
      xit "assigns a newly created but unsaved website as @website" do
        # Trigger the behavior that occurs when invalid params are submitted
        # Website.any_instance.stub(:save).and_return(false)
        # post :create, {:website => {}}, valid_session
        # assigns(:website).should be_a_new(Website)
      end

      xit "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        # Website.any_instance.stub(:save).and_return(false)
        # post :create, {:website => {}}, valid_session
        # response.should render_template("new")
      end
    end
  end

end
